"""scrap_stock_raw_material_support

Revision ID: 0aa3f9e67480
Revises: 9415a1f19c42
Create Date: 2026-02-27 17:22:58.645647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa3f9e67480'
down_revision: Union[str, None] = '9415a1f19c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrap_stock', sa.Column('raw_material_id', sa.UUID(), nullable=True))
    op.alter_column('scrap_stock', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_scrap_product_type', 'scrap_stock', type_='unique')
    op.create_foreign_key(None, 'scrap_stock', 'raw_materials', ['raw_material_id'], ['id'])
    op.add_column('scrap_stock_transactions', sa.Column('raw_material_id', sa.UUID(), nullable=True))
    op.alter_column('scrap_stock_transactions', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'scrap_stock_transactions', 'raw_materials', ['raw_material_id'], ['id'])
    op.add_column('shift_scrap_usage', sa.Column('raw_material_id', sa.UUID(), nullable=True))
    op.alter_column('shift_scrap_usage', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'shift_scrap_usage', 'raw_materials', ['raw_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_scrap_usage', type_='foreignkey')
    op.alter_column('shift_scrap_usage', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('shift_scrap_usage', 'raw_material_id')
    op.drop_constraint(None, 'scrap_stock_transactions', type_='foreignkey')
    op.alter_column('scrap_stock_transactions', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('scrap_stock_transactions', 'raw_material_id')
    op.drop_constraint(None, 'scrap_stock', type_='foreignkey')
    op.create_unique_constraint('uq_scrap_product_type', 'scrap_stock', ['finished_product_id', 'stock_type'])
    op.alter_column('scrap_stock', 'finished_product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('scrap_stock', 'raw_material_id')
    # ### end Alembic commands ###
