"""add_is_auto_to_financial_transactions

Revision ID: 13384101e3db
Revises: 8c4ad30d3f1f
Create Date: 2026-02-26 11:46:06.774137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13384101e3db'
down_revision: Union[str, None] = '8c4ad30d3f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_transactions', sa.Column('is_auto', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_transactions', 'is_auto')
    # ### end Alembic commands ###
