"""remove machine maintenance relationship

Revision ID: 429ce6ade3b4
Revises: 30274b99e65e
Create Date: 2026-01-21 15:33:13.829793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429ce6ade3b4'
down_revision: Union[str, None] = '30274b99e65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
