"""add_is_paid_to_leave_requests

Revision ID: 632a4a19600c
Revises: 13384101e3db
Create Date: 2026-02-26 12:39:03.990465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632a4a19600c'
down_revision: Union[str, None] = '13384101e3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'is_paid')
    # ### end Alembic commands ###
