"""add scrap stock and shift enhancements

Revision ID: 830b19ad2aec
Revises: 38b671f5317b
Create Date: 2026-02-27 14:40:18.691355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830b19ad2aec'
down_revision: Union[str, None] = '38b671f5317b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap_stock',
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_product_id')
    )
    op.create_index(op.f('ix_scrap_stock_id'), 'scrap_stock', ['id'], unique=False)
    op.create_table('scrap_stock_transactions',
    sa.Column('scrap_stock_id', sa.UUID(), nullable=False),
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['scrap_stock_id'], ['scrap_stock.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_stock_transactions_id'), 'scrap_stock_transactions', ['id'], unique=False)
    op.create_table('shift_pauses',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=False),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_pauses_id'), 'shift_pauses', ['id'], unique=False)
    op.create_table('shift_scrap_usage',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_scrap_usage_id'), 'shift_scrap_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_scrap_usage_id'), table_name='shift_scrap_usage')
    op.drop_table('shift_scrap_usage')
    op.drop_index(op.f('ix_shift_pauses_id'), table_name='shift_pauses')
    op.drop_table('shift_pauses')
    op.drop_index(op.f('ix_scrap_stock_transactions_id'), table_name='scrap_stock_transactions')
    op.drop_table('scrap_stock_transactions')
    op.drop_index(op.f('ix_scrap_stock_id'), table_name='scrap_stock')
    op.drop_table('scrap_stock')
    # ### end Alembic commands ###
