"""Add warehouse tables

Revision ID: a49101c80e05
Revises: 21df39a0374f
Create Date: 2026-01-20 16:33:28.881314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49101c80e05'
down_revision: Union[str, None] = '21df39a0374f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_materials_id'), 'raw_materials', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=9), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('warehouse_receipts',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_index(op.f('ix_warehouse_receipts_id'), 'warehouse_receipts', ['id'], unique=False)
    op.create_table('warehouse_stock',
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_material_id')
    )
    op.create_index(op.f('ix_warehouse_stock_id'), 'warehouse_stock', ['id'], unique=False)
    op.create_table('material_requests',
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_id'), 'material_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_requests_id'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_warehouse_stock_id'), table_name='warehouse_stock')
    op.drop_table('warehouse_stock')
    op.drop_index(op.f('ix_warehouse_receipts_id'), table_name='warehouse_receipts')
    op.drop_table('warehouse_receipts')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_raw_materials_id'), table_name='raw_materials')
    op.drop_table('raw_materials')
    # ### end Alembic commands ###
