"""Add production tables

Revision ID: cade50389813
Revises: a49101c80e05
Create Date: 2026-01-21 00:50:10.257790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cade50389813'
down_revision: Union[str, None] = 'a49101c80e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_reasons',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_defect_reasons_id'), 'defect_reasons', ['id'], unique=False)
    op.create_table('finished_products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('standard_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_products_id'), 'finished_products', ['id'], unique=False)
    op.create_table('production_lines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    op.create_table('finished_product_stock',
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_product_id')
    )
    op.create_index(op.f('ix_finished_product_stock_id'), 'finished_product_stock', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('production_line_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('production_line_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('defective_products',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('defect_reason_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['defect_reason_id'], ['defect_reasons.id'], ),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defective_products_id'), 'defective_products', ['id'], unique=False)
    op.create_table('production_outputs',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('finished_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('produced_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['finished_products.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_outputs_id'), 'production_outputs', ['id'], unique=False)
    op.create_table('production_records',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_id'), 'production_records', ['id'], unique=False)
    op.create_table('shift_handovers',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.Column('equipment_status', sa.Text(), nullable=True),
    sa.Column('pending_issues', sa.Text(), nullable=True),
    sa.Column('next_shift_instructions', sa.Text(), nullable=True),
    sa.Column('handover_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id')
    )
    op.create_index(op.f('ix_shift_handovers_id'), 'shift_handovers', ['id'], unique=False)
    op.create_table('shift_machines',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_machines_id'), 'shift_machines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_machines_id'), table_name='shift_machines')
    op.drop_table('shift_machines')
    op.drop_index(op.f('ix_shift_handovers_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    op.drop_index(op.f('ix_production_records_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_production_outputs_id'), table_name='production_outputs')
    op.drop_table('production_outputs')
    op.drop_index(op.f('ix_defective_products_id'), table_name='defective_products')
    op.drop_table('defective_products')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_finished_product_stock_id'), table_name='finished_product_stock')
    op.drop_table('finished_product_stock')
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_finished_products_id'), table_name='finished_products')
    op.drop_table('finished_products')
    op.drop_index(op.f('ix_defect_reasons_id'), table_name='defect_reasons')
    op.drop_table('defect_reasons')
    # ### end Alembic commands ###
